name: CI

on:
  # At any commit in master
  push:
    branches:
      - 'master'

jobs:
  # Build by Maven and check tests
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -DskipTests

    - name: Maven Verify
      run: mvn -B clean verify

  # Publish to GitHub Docker Registry
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:

      # Build JAR
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean compile package

      # Set global environment variables
      - name: set global env
        id: global_env
        run: |
          echo "::set-output name=IMAGE_NAME::httpstatusmocker"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/alnat/httpstatusmocker/httpstatusmocker"

      # Build Docker image
      - name: Build and tag image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .

      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      # Publish image
      - name: Publish image
        env:
          IMAGE_NAME: alnat/httpstatusmocker:latest
        run: docker push "docker.pkg.github.com/alnat/httpstatusmocker/${{ steps.global_env.outputs.IMAGE_NAME }}"
